name: Windows Dolphin Builder

on:
  workflow_dispatch: # Allows manual dispatch of the workflow

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          submodules: true # Ensures submodules are checked out
          fetch-depth: 0 # Ensures the full repository is checked out

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@v2
        with:
          nuget-version: latest

      - name: Verify SDL-UWP.vcxproj file exists
        shell: pwsh
        run: |
          Write-Output "Verifying SDL-UWP.vcxproj file..."
          if (-Not (Test-Path "Externals/SDL/SDL/VisualC-WinRT/SDL-UWP.vcxproj")) {
            Write-Error "SDL-UWP.vcxproj not found!"
            exit 1
          }
          Write-Output "SDL-UWP.vcxproj found."

      - name: Build and Package Dolphin UWP Project
        run: |
          echo "Building and packaging the Dolphin UWP project..."
          cd Source
          msbuild dolphin-emu.sln /p:Configuration=Release /p:Platform=x64 /t:Restore,Build /p:RestorePackagesConfig=true /p:AppxPackageSigningEnabled=true /p:PackageCertificateKeyFile="DolphinWinRT_TemporaryKey.pfx" /p:DeployOnBuild=true /p:DeployTargetDevice=RemoteMachine /p:RemoteDebugMachine="XBOX"
          echo "Build and packaging completed."

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Dolphin-UWP-Build
          path: Source/bin/Release
